//centered lines
#define CHAR_CENTERED_LINE_VERTICAL			0xE02E
#define CHAR_CENTERED_LINE_HORIZONTAL		0xE02F

#define CHAR_CENTERED_LINE_L_TOP_LEFT		0xE00B
#define CHAR_CENTERED_LINE_L_TOP_RIGHT		0xE00D
#define CHAR_CENTERED_LINE_L_BOTTOM_LEFT	0xE02B
#define CHAR_CENTERED_LINE_L_BOTTOM_RIGHT	0xE02D
#define CHAR_CENTERED_LINE_T_NOTOP			0xE00C
#define CHAR_CENTERED_LINE_T_NOBOTTOM		0xE02C
#define CHAR_CENTERED_LINE_T_NOLEFT			0xE01B
#define CHAR_CENTERED_LINE_T_NORIGHT		0xE01D
#define CHAR_CENTERED_LINE_CROSS			0xE01C

